

const flats = [
  {
    id: "flat1",
    title: "Cozy 2BHK Near Delhi University",
    description:
      "Well-furnished apartment with modern amenities, perfect for students. Close to metro station and campus.",
    rent: 15000,
    location: {
      address: "Kamla Nagar, Delhi University, New Delhi",
      coordinates: [28.6692, 77.2065],
    },
    amenities: ["WiFi", "Parking", "Laundry", "Kitchen", "Furnished", "Security"],
    images: ["/assets/modern-apartment-living.png"],
    ownerId: "owner1",
    ownerName: "Rahul Verma",
    roommates: [], // Will be filled with user info when booked
    availableFrom: "2024-01-15",
    flatType: "room-with-roommates",
  },
  {
    id: "flat2",
    title: "Single Room in Shared Flat",
    description: "Private room in a 3BHK flat with common areas. Great for focused study environment.",
    rent: 8000,
    location: {
      address: "Mukherjee Nagar, Delhi",
      coordinates: [28.7041, 77.2025],
    },
    amenities: ["WiFi", "Kitchen", "Study Room", "Furnished"],
    images: ["/assets/single-room.png"],
    ownerId: "owner2",
    ownerName: "Neha Sharma",
    roommates: [],
    availableFrom: "2024-02-01",
    flatType: "room-only",
  },
  {
    id: "flat3",
    title: "Premium Student Housing with Gym",
    description: "Luxury student accommodation with all modern facilities including gym and swimming pool.",
    rent: 25000,
    location: {
      address: "Rajouri Garden, New Delhi",
      coordinates: [28.6467, 77.1206],
    },
    amenities: ["WiFi", "Parking", "Laundry", "Kitchen", "Gym", "Swimming Pool", "Security", "Air Conditioning"],
    images: ["/assets/luxury-student-housing.png"],
    ownerId: "owner3",
    ownerName: "Arjun Singh",
    roommates: [],
    availableFrom: "2024-01-20",
    flatType: "room-with-roommates",
  },
  {
    id: "flat4",
    title: "Budget-Friendly Room Near Campus",
    description: "Affordable accommodation for students on a budget. Basic amenities with good connectivity.",
    rent: 6000,
    location: {
      address: "Laxmi Nagar, Delhi",
      coordinates: [28.6345, 77.2767],
    },
    amenities: ["WiFi", "Kitchen", "Furnished"],
    images: ["/assets/budget-room.png"],
    ownerId: "owner4",
    ownerName: "Pooja Mehta",
    roommates: [],
    availableFrom: "2024-01-10",
    flatType: "room-only",
  },
  {
    id: "flat5",
    title: "Spacious 3BHK with Study Areas",
    description: "Large apartment with dedicated study spaces and common areas. Perfect for serious students.",
    rent: 18000,
    location: {
      address: "Karol Bagh, New Delhi",
      coordinates: [28.6519, 77.1909],
    },
    amenities: ["WiFi", "Parking", "Laundry", "Kitchen", "Study Room", "Furnished", "Security"],
    images: ["/assets/spacious-apartment-study.png"],
    ownerId: "owner5",
    ownerName: "Karan Malhotra",
    roommates: [],
    availableFrom: "2024-02-15",
    flatType: "room-with-roommates",
  },
  {
    id: "flat6",
    title: "Modern Studio Apartment",
    description: "Contemporary studio with all amenities included. Perfect for independent living.",
    rent: 12000,
    location: {
      address: "Janakpuri, New Delhi",
      coordinates: [28.6219, 77.0757],
    },
    amenities: ["WiFi", "Kitchen", "Furnished", "Air Conditioning"],
    images: ["/assets/modern-studio-apartment.png"],
    ownerId: "owner6",
    ownerName: "Ritika Jain",
    roommates: [],
    availableFrom: "2024-01-25",
    flatType: "room-only",
  },
]

module.exports = { flats }